name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]


jobs:

  ci:
    runs-on: ubuntu-latest
    environment: ci

    steps:
    - uses: actions/checkout@v3
    - name: deps
      run: |
        npm install
          
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/website:latest

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push to Docker Hub 
      run: |
        docker push ffr03/website:latest

